### ISSUE TITLE
Argument error while ruuning on a custom dataset

### ISSUE THREAD

**Issue by anirban-code-to-live** [akanimax/pro-gan#4]
I modified the mnist.conf file and I was trying to run the model using the following command:
python train_network.py --config=configs/mnist.conf

But it is showing some argument error like this -

Traceback (most recent call last):
  File "train_network.py", line 145, in <module>
    main(parse_arguments())
  File "train_network.py", line 100, in main
    device=device
  File "/home1/harsh_csa/.local/lib/python2.7/site-packages/pro_gan_pytorch/PRO_GAN.py", line 373, in __init__
    self.loss = self.__setup_loss(loss)
  File "/home1/harsh_csa/.local/lib/python2.7/site-packages/pro_gan_pytorch/PRO_GAN.py", line 407, in __setup_loss
    loss = losses.LSGAN(self.dis)
  File "/home1/harsh_csa/.local/lib/python2.7/site-packages/pro_gan_pytorch/Losses.py", line 169, in __init__
    super().__init__(dis)
TypeError: super() takes at least 1 argument (0 given)

**Comment by akanimax** [comment]
Hi @anirban-code-to-live, 
Apology for late reply. It has been a difficult for me to cope up all the issues. Your error is that you are using python2.7 with this repo. The code is specific to python versions 3.5+. Could you please set up a 3.5 pyvenv?
Best regards,
@akanimax
